// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace CapitalRequest.API.DataAccess.Models;

public class Attachment
{
    public int Id { get; set; }

    public int ProposalId { get; set; }

    public string FileName { get; set; }

    public int? ProvidedInfoId { get; set; }

    public DateTime? DateUploaded { get; set; }
}