// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CapitalRequest.API.Models;
using System;
using System.Collections.Generic;

namespace CapitalRequestAPI.Models;

public class Asset
{
    public int Id { get; set; }

    public int ProposalId { get; set; }

    public string AssetNumber { get; set; }

    public bool? IsClinicalEquipment { get; set; }

    public bool? IsReplacement { get; set; }

    public bool? IsTransfer { get; set; }

    public bool? IsScrapped { get; set; }

    public bool? NeedCertification { get; set; }

    public virtual Proposal Proposal { get; set; }
}