// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapitalRequest.API.Models;

public class CapitalPoolIdentifier
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string ShortName { get; set; }

    public bool? IsWbs { get; set; }

    public int? SortOrder { get; set; }

    public int? ItemOrder { get; set; }
}
