// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace CapitalRequest.API.Models;

public partial class EmailTemplate
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Subject { get; set; }

    public string Body { get; set; }

    public bool? IsGroup { get; set; }

    public string OptionType { get; set; }

    public string Priority { get; set; }

    public bool? HasNoGroup { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? Updated { get; set; }

    public string UpdatedBy { get; set; }
}