// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapitalRequest.API.Models;

public class ProjectType
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string ShortName { get; set; }
    public string GLNumber { get; set; }
}
