// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapitalRequest.API.Models;

public partial class ProvidedInfo
{
    public int Id { get; set; }

    public int RequestedInfoId { get; set; }

    public int ReviewerGroupId { get; set; }

    public int? ReviewerId { get; set; }

    public string ProvidedInformation { get; set; }

    public string Action { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? Updated { get; set; }

    public string UpdatedBy { get; set; }
}