// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace CapitalRequest.API.Models;

public class Quote
{
    public int Id { get; set; }

    public int ProposalId { get; set; }

    public string FileName { get; set; }

    public DateTime DateUploaded { get; set; }

}