// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace CapitalRequest.API.Models;

public class Reviewer
{
    public int Id { get; set; }

    public string UserId { get; set; }

    public string Email { get; set; }

    public int? RegionId { get; set; }

    public int? SegmentId { get; set; }

    public string FullName { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int? ReviewerGroupId { get; set; }

    public bool? IsVpOfOps { get; set; }

    public int? StepNumber { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? Updated { get; set; }

    public string UpdatedBy { get; set; }
}