// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace CapitalRequestAPI.Models
{
    public class ReviewerGroup
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public int? EmailTemplateId { get; set; }

        public string ReviewerType { get; set; }

        public int? StepNumber { get; set; }

        public int? DashboardOrder { get; set; }

        public bool? AdminReviewer { get; set; }

        public DateTime? Created { get; set; }

        public string CreatedBy { get; set; }

        public DateTime? Updated { get; set; }

        public string UpdatedBy { get; set; }
    }
}