// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CapitalRequest.API.Models;
using System;
using System.Collections.Generic;

namespace CapitalRequestAPI.Models;

public class Wbs
{
    public int Id { get; set; }

    public int ProposalId { get; set; }

    public int? TypeOfProject { get; set; }

    public string Wbsnumber { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? Updated { get; set; }

    public string UpdatedBy { get; set; }

    public virtual Proposal Proposal { get; set; }
}